apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
- hpa.yaml
- canary.yaml
namespace: production
images:
- name: vfarcic/devops-toolkit-series
  newName: vfarcic/devops-toolkit-series
  newTag: 2.7.0
